import type { IWorkoutRepository } from "@/src/repositories/WorkoutRepository";
import type { IBodyRepository } from "@/src/repositories/BodyRepository";
import type { IHealthRepository } from "@/src/repositories/HealthRepository";
import type { IDietRepository } from "@/src/repositories/DietRepository";
import type { IPantryRepository } from "@/src/repositories/PantryRepository";
import type { INotesRepository } from "@/src/repositories/NotesRepository";
import type {
  WorkoutSession,
  BodyReading,
  HealthSnapshot,
  DietEntry,
  NoteEntry,
  PantryItem,
} from "@/src/types";
import { localDateString, type DayPlan } from "@/src/services/ScheduleService";

export interface CoachData {
  date: string;
  dayPlan: DayPlan;
  sessions: WorkoutSession[]; // last 7
  body: BodyReading[]; // last 14
  health: HealthSnapshot[]; // last 7
  diet: DietEntry[]; // last 7
  notes: NoteEntry[]; // last 3
  pantryLow: string[];
  pantryOut: string[];
  pantryStockedCount: number;
}

/** ~4 chars per token is a good-enough estimate for size guarding. */
export function estimateTokens(text: string): number {
  return Math.ceil(text.length / 4);
}

export class CoachService {
  constructor(
    private readonly workouts: IWorkoutRepository,
    private readonly body: IBodyRepository,
    private readonly health: IHealthRepository,
    private readonly diet: IDietRepository,
    private readonly pantry: IPantryRepository,
    private readonly notes: INotesRepository
  ) {}

  async gather(dayPlan: DayPlan): Promise<CoachData> {
    const [sessions, body, health, diet, notes, pantryItems] =
      await Promise.all([
        this.workouts.getAll(),
        this.body.getAll(),
        this.health.getAll(),
        this.diet.getAll(),
        this.notes.getAll(),
        this.pantry.getAll(),
      ]);

    return {
      date: localDateString(),
      dayPlan,
      sessions: sessions.slice(-7),
      body: body.slice(-14),
      health: health.slice(-7),
      diet: diet.slice(-7),
      notes: notes.slice(-3),
      pantryLow: pantryItems
        .filter((p: PantryItem) => p.status === "low")
        .map((p) => p.item),
      pantryOut: pantryItems
        .filter((p: PantryItem) => p.status === "out")
        .map((p) => p.item),
      pantryStockedCount: pantryItems.filter(
        (p: PantryItem) => p.status === "stocked"
      ).length,
    };
  }

  /** Pure — assembles the Claude-ready coaching context (PROMPT.md structure). */
  assemble(d: CoachData): string {
    const todayDiet = d.diet.find((e) => e.d === d.date);
    const proteinToday = todayDiet
      ? todayDiet.meals.reduce((s, m) => s + m.p, 0) || todayDiet.p_tot
      : 0;

    return `# RATNA — COACH CONTEXT (auto-generated by fitness-tracker PWA)

You are an AI fitness coach for Ratna. This message contains everything current — no file uploads needed.

## WHO
Male, training since 2026-01-03. Goal: body recomp — reduce waist fat, build visible muscle (capped delts, leaner waist, fuller chest). Commercial gym, AM sessions 50-60 min. BJJ Mon/Wed/Fri 7 PM. Hybrid job (office Tue + 2nd Fri). Cooks for 2 (Ratna + Neha, Indian/Asian/Italian). No fish for Ratna.

## COACHING RULES
- Be specific: exact weights and reps ("do 35×10"), not ranges.
- Use the most recent session data below for next-session targets.
- Flag issues once with a fix; don't lecture.
- Priorities: 1) progressive overload on leg press, OHP, incline DB press, rows 2) protein ≥130g/day (shake=anchor, 79g) 3) weigh-in consistency 4) dinner before 19:30 (18:30 BJJ days) 5) never 3+ consecutive training days 6) waist_cm tracking.
- OHP rule: start at 35 on push days; do not attempt 40 until 35×10×3 is solid 2 sessions in a row with no BJJ the night before.
- After BJJ nights expect grip/shoulder fatigue carryover; recovery red = shorten or rest.

## DATA CONVENTIONS
Workout weights: machine/cable = displayed stack; leg_press = lb/side; db = lb/hand; bb = plates/side excl. bar; tbar = total plates; wu = warmup; sets = [weight, reps].
Scale: VeSync BIA — bf% is a DIRECTIONAL TREND ONLY (algorithm skews for Ratna's body type); use 4-week windows. Weight lb and muscle_mass_lb are more reliable. waist in cm.

## TODAY (${d.date})
Day type: ${d.dayPlan.dayType} — ${d.dayPlan.headline}
Protein logged so far: ${proteinToday}g / 130g target (160 ideal)

## LAST ${d.sessions.length} WORKOUT SESSIONS
${JSON.stringify(d.sessions)}

## BODY READINGS (last ${d.body.length})
${JSON.stringify(d.body)}

## HEALTH SNAPSHOTS (Apple Watch/Health, last ${d.health.length})
${d.health.length > 0 ? JSON.stringify(d.health) : "none yet"}

## DIET (last ${d.diet.length} logged days)
${JSON.stringify(d.diet)}

## RECENT SESSION NOTES
${d.notes.length > 0 ? JSON.stringify(d.notes) : "none"}

## PANTRY
Stocked items: ${d.pantryStockedCount}. Low: ${d.pantryLow.length > 0 ? d.pantryLow.join(", ") : "nothing"}. Out: ${d.pantryOut.length > 0 ? d.pantryOut.join(", ") : "nothing"}.

## MY QUESTION
`;
  }
}
